name: Build and Deploy Container to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: WEBAPPB
  ACR_NAME: acraula131         # substituir pelo nome do ACR quando disponível
  IMAGE_NAME: gamestar-api

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest \
            .

      - name: Push Docker Image
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Configure Azure Web App environment variables
        run: |
          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group rg-python-aula \
            --settings \
              APP_ENV=production \
              LOG_JSON=true \
              WEBSITES_PORT=8000 \
              SECRET_KEY="${{ secrets.SECRET_KEY }}" \
              DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              GITHUB_CLIENT_ID="${{ secrets.GITHUB_CLIENT_ID }}" \
              GITHUB_CLIENT_SECRET="${{ secrets.GITHUB_CLIENT_SECRET }}" \
              GITHUB_REDIRECT_URI="https://webappb-cuf4gxhvh6hmb0h3.chilecentral-01.azurewebsites.net/api/v1/auth/github/callback"

      - name: Deploy Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
